name: 编译和发布 qBittorrent
on:
  workflow_dispatch:
    inputs:
      QBITTORRENT_BRANCH:
        description: 'qBittorrent 版本'
        default: '4.5.4'
        type: number
        required: true

      QT_VER_PREFIX:
        description: 'qt 版本：'
        default: '6'
        type: number
        required: true
        options: [ 5, 6 ]

      LIBTORRENT_BRANCH:
        description: 'libtorrent 版本：'
        default: '1.2.9'
        type: number
        required: true
        options: [ '1.2.19', '2.0.9' ]

      try:
        description: '下载错误重试次数：'
        default: '5'
        type: number
        required: true

      sleep_time:
        description: '每次下载错误时重试间隔：'
        default: '30'
        type: number
        required: true

jobs:

  create-prerelease:
    name: Create Prerelease
    # if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date --gmt +0800)" >> $GITHUB_ENV
        
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        continue-on-error: true
        with:
          delete_release: true
          tag_name: qbittorrent-nox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Prerelease Tag
        continue-on-error: true
        id: create_prerelease_tag
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: false
          tag_name: qbittorrent-nox
          name: Continuous build
          body: |
            Building time: ${{ env.NOW }}
            - - -

  static-build:
    runs-on: ubuntu-latest
    container: "abcfy2/muslcc-toolchain-ubuntu:${{ matrix.cross_host }}"
    env:
      try: ${{github.event.inputs.try}}
      CROSS_HOST: ${{ matrix.cross_host }}
      sleep_time: ${{github.event.inputs.sleep_time}}
      QT_VER_PREFIX: ${{github.event.inputs.QT_VER_PREFIX}}
      LIBTORRENT_BRANCH: ${{github.event.inputs.LIBTORRENT_BRANCH}}
      QBITTORRENT_BRANCH: ${{github.event.inputs.QBITTORRENT_BRANCH}}
    strategy:
      fail-fast: false
      matrix:
        cross_host:
          - arm-linux-musleabi
          # - arm-linux-musleabihf
          - aarch64-linux-musl
          - mips-linux-musl
          - mipsel-linux-musl
          - mips64-linux-musl
          - mips64el-linux-musl
          - x86_64-linux-musl
          # - i686-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 交叉编译 qbittorrent-nox-static
        id: organize
        run: |
          if [ "${GITHUB_EVENT_NAME}" = release ]; then
            export qBittorrent_VER="${GITHUB_REF#refs/*/}"
            echo "qBittorrent_VER=${qBittorrent_VER}" >> $GITHUB_ENV
          fi
          .github/workflows/cross_build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: qbittorrent-nox_${{ matrix.cross_host }}_static
          path: /tmp/*qbittorrent-nox*

      - name: 上传 Github Assets
        continue-on-error: true
        if: steps.organize.conclusion == 'success'
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: /tmp/${{env.TARGET_ARCH}}*
          tag_name: qbittorrent-nox
          name: qbittorrent-nox
          append_body: true
